version: "3.9"

services:
  plc-redis:
    image: redis
    container_name: plc-redis
    ports:
      - "6379:6379"
    volumes:
      - plc-redis-data:/data
  
  plc-db:
    image: mysql
    container_name: plc-db
    environment:
      MYSQL_ROOT_PASSWORD: "@dmin1234"
    ports:
      - "3306:3306"
    volumes:
      - plc-db-data:/var/lib/mysql

  plc-service:
    image: plc-service
    container_name: plc-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SelectedDatabase=Local"
      - "ConnectionStrings:Local=server=plc-db; port=3306; database=plcCapstone; user=root; password=@dmin1234; Persist Security Info=False; Connect Timeout=300"
      - "CacheSettings:ConnectionString=plc-redis:6379"
    depends_on:
      - plc-redis
      - plc-db
    ports:
      - "7133:80"

volumes:
  plc-redis-data:
  plc-db-data:
