version: "3.9"

services:
  plcdb:
    image: mysql
    container_name: plcdb
    environment:
      MYSQL_ROOT_PASSWORD: "@dmin1234"
    ports:
      - "3306:3306"
    volumes:
      - plc-db-data:/var/lib/mysql

  plcbase:
    image: plc-base
    container_name: plcbase
    build: ./
    environment:
      - "SelectedDatabase=Local"
      - "ConnectionStrings:Local=server=plcdb; port=3306; database=plcCapstone; user=root; password=@dmin1234; Persist Security Info=False; Connect Timeout=300"
    depends_on:
      - plcdb
    ports:
      - 7133:80

volumes:
  plc-db-data:
