name: Deploy PLC Base
on:
  push:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker rm -f $(docker ps -a -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }})
            docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:latest
            docker run -d -p ${{ secrets.APP_PORT }}:80 --name test-plc ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}
